name: Patch VBMeta

on:
  workflow_dispatch:
    inputs:
      Architecture:
        description: 'Architecture'
        required: true
        default: x86_64

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install click

      - name: Patch vbmeta.img
        run: |
          curl -O https://raw.githubusercontent.com/libxzr/vbmeta-disable-verification/main/vbmeta-disable-verification.py
          python3 vbmeta-disable-verification.py vbmeta.img vbmeta-patched.img

      - name: Upload patched vbmeta
        uses: actions/upload-artifact@v4
        with:
          name: vbmeta-patched
          path: vbmeta-patched.img
